import { useBananaCakePop } from "@chillicream/bananacakepop-server-adapter-plugin";
import { createYoga } from "graphql-yoga";
import { createServer } from "node:http";
import { getSchema } from "./schema"; // Will be generated by Grats

/** @gqlType */
type Query = unknown;

/** @gqlField */
export function hello(_: Query): string {
  return "Hello world!";
}

const yoga = createYoga({
  schema: getSchema(),
  plugins: [useBananaCakePop()],
  graphiql: false,
});

const server = createServer(yoga);

server.listen(4000, () => {
  console.log("Running a GraphQL API server at http://localhost:4000/graphql");
});
